#ifndef OPENFLIGHTCOMPUTER_FAULT_CATALOG_H
#define OPENFLIGHTCOMPUTER_FAULT_CATALOG_H

#include "fault.h"

#include <stddef.h>

enum {
    FAULT_ID_MCU_INITIALIZATION = 1U,
    FAULT_ID_CLOCK_CONFIGURATION = 2U,
    FAULT_ID_CLOCK_FREQUENCY = 3U,
    FAULT_ID_TIMEBASE_CONFIGURATION = 4U,
    FAULT_ID_TASK_REGISTRATION = 5U,
    FAULT_ID_SCHEDULER_INITIALIZATION = 6U,
    FAULT_ID_SCHEDULER_RUNTIME = 7U,
    FAULT_ID_STATE_MACHINE_TRANSITION = 8U,
    FAULT_ID_FAULT_CLOCK_ATTACHMENT = 9U,
    FAULT_ID_LOGGING_CLOCK_ATTACHMENT = 10U,
    FAULT_ID_USB_LOGGING_INITIALIZATION = 11U,
};

const fault_definition_t *firmware_fault_catalog(size_t *definition_count);

#endif
