#ifndef OPENFLIGHTCOMPUTER_FLIGHTCOMPUTER_V1_BOARD_DEFINITION_H
#define OPENFLIGHTCOMPUTER_FLIGHTCOMPUTER_V1_BOARD_DEFINITION_H

#include "board_usb.h"

#define FLIGHTCOMPUTER_V1_BOARD_ID "flightcomputer-v1"
#define FLIGHTCOMPUTER_V1_BOARD_NAME "Flight Computer V1"
#define FLIGHTCOMPUTER_V1_MANUFACTURING_REVISION "1.7"
#define FLIGHTCOMPUTER_V1_SCHEMATIC_REVISION "0.1"
#define FLIGHTCOMPUTER_V1_MCU_MODEL "STM32F405RGT6"

#define FLIGHTCOMPUTER_V1_HSE_FREQUENCY_HZ 16000000U
#define FLIGHTCOMPUTER_V1_SYSTEM_CLOCK_FREQUENCY_HZ 168000000U
#define FLIGHTCOMPUTER_V1_TIMEBASE_TIMER_CLOCK_FREQUENCY_HZ 84000000U
#define FLIGHTCOMPUTER_V1_TIMEBASE_COUNTER_FREQUENCY_HZ 1000000U
#define FLIGHTCOMPUTER_V1_TIMEBASE_INTERRUPT_PRIORITY 0U

/* The V1 divider produces too little voltage for OTG FS VBUS detection. */
#define FLIGHTCOMPUTER_V1_USB_VBUS_MODE BOARD_USB_VBUS_MODE_ASSUME_PRESENT

#endif
