#ifndef OPENFLIGHTCOMPUTER_BOOTLOADER_CONTRACT_H
#define OPENFLIGHTCOMPUTER_BOOTLOADER_CONTRACT_H

#include <stdint.h>

#define OFC_BOOTLOADER_FLASH_START UINT32_C(0x08000000)
#define OFC_BOOTLOADER_FLASH_LENGTH UINT32_C(0x00010000)
#define OFC_APPLICATION_FLASH_START UINT32_C(0x08010000)
#define OFC_APPLICATION_METADATA_ADDRESS UINT32_C(0x080DFF00)
#define OFC_CONFIGURATION_FLASH_START UINT32_C(0x080E0000)
#define OFC_APPLICATION_MAXIMUM_LENGTH \
    (OFC_APPLICATION_METADATA_ADDRESS - OFC_APPLICATION_FLASH_START)

#define OFC_BOOTLOADER_REQUEST_MAGIC UINT32_C(0x4F464355)
#define OFC_APPLICATION_METADATA_MAGIC UINT32_C(0x4F464341)
#define OFC_APPLICATION_METADATA_VERSION UINT32_C(1)

typedef struct {
    uint32_t magic;
    uint32_t format_version;
    uint32_t image_length;
    uint32_t image_crc32;
} ofc_application_metadata_t;

#endif
